### ISSUE TITLE
Submit button hidden

### ISSUE THREAD

**Issue by ebugnet** [jhoopes/moodle-mod_activequiz#10]
In moodle 2.9, theme More

The submit button is not visible in the bottom of the setting page.

Submit buton are in a fieldste with class="hidden".
You can see them and use them by playing in css and uncheck hidden.

Éric

**Comment by jhoopes** [comment]
Hi Eric,

My apologies on this.  Moodle uses the .hidden class in its forms, which unknowing to me, when I added my own hidden class to the plugin ended up hiding all of the form elements.  This should now be fixed.

Thanks,

**Comment by ebugnet** [comment]
Hi, no problem !
Tested and approved... It works now.
Thanks

2015-06-04 23:34 GMT+02:00 jhoopes <notifications@github.com>:

> Hi Eric,
>
> My apologies on this. Moodle uses the .hidden class in its forms, which
> unknowing to me, when I added my own hidden class to the plugin ended up
> hiding all of the form elements. This should now be fixed.
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhoopes/moodle-mod_activequiz/issues/10#issuecomment-109060970>
> .
>



-- 

[image: http://eric.bugnet.fr] <http://eric.bugnet.fr>
eric.bugnet.fr
