### ISSUE TITLE
Hard-coded English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [jhoopes/moodle-mod_activequiz#13]
Hi,
I love this plugin.

But there are some hard-coded English language strings used. It would be best if these were declared as variables, so that AMOS can be used to fully translate this plugin into other languages.
I translated this plugin in AMOS into Mexican Spanish, but found a couple of English hard-coded strings. The first one:

When the teacher is informed 'Waiting for the question to be sent in'... seconds  THE TIME SHOWN IS xx seconds (the word 'seconds' is hard-wired).

I will post the other strings I found as soon as can run it with students.

Thanks in advance for your help.

**Comment by germanvaleroelizondo** [comment]
Another hard-coded string: 'regrade all grades' text inside the button.

And: 'Successfully re-graded quiz' message

Thanks in advance for your help.

**Comment by ebugnet** [comment]
Ther is « question list » too.
Thanks

**Comment by Kathrin84** [comment]
I created a pull request for this issue because we would like to integrate this plugin into our productive Moodle.
https://github.com/jhoopes/moodle-mod_activequiz/pull/17
