### ISSUE TITLE
sort by category seems not work !

### ISSUE THREAD

**Issue by gillest1** [jhoopes/moodle-mod_activequiz#15]
Hi ! 
Thanks for this module.

In moodle 2.7 , theme CLEAN,
when I "edit quizz", All platform questions are listed. 

There are more than 9000 questions on my platform. All of them appear in the list. Sort by category seems not works.  It's hard to find the question I want to add in my quizz. 

Thanks for your help.

**Comment by jhoopes** [comment]
Hi Gillest, 

This is now fixed in the newest 27 stable update.  Please let me know if you have any issues.  I'll be updating moodle.org with this soon.
