### ISSUE TITLE
Feature Request: Make it possible to anonymize Answers in quiz

### ISSUE THREAD

**Issue by Kathrin84** [jhoopes/moodle-mod_activequiz#16]
Hi,

I've tested your plugin and I like it very much. We discussed it with some of our key users and we think that your plugin could also be used as an audience response system. 
So a teacher could for example ask if students understood the content of the lesson and he could get a feedback via your active quiz plugin. 
However, if it would be visible to him who of the students gave a specific answer, the students won't probably give an honest answer.

So it would be great if the plugin could be extended with an anonymous vote function. This should be really anonymous and not be revealable by the teacher at a later time.

It would be important that the quiz is done in anonymous mode is also shown to the participants, so that they won't fear honest answers.

Kind regards,
Kathrin

**Comment by jhoopes** [comment]
Hi Kathrine,

I agree that'd be a great feature to have for audience responses.  Are you thinking that instead of having a student's/user's name appear in the list of responses, just blocking them out?

Also, are you thinking in terms of multiple choice questions or other types of questions?

Thanks,

**Comment by Kathrin84** [comment]
Hi,

the names of the students could be blocked out. It is important that the trainer could not reveal the names to the students afterwards. That mode should be entirely anonymized. That helps that students feel free to answer honestly and the trainer gets a more representative feedback.

Multiple Choice should be the question type that is predestinated to use together with audience responses. But it would be nice if the other question types could also be used in the anonymized mode.

Greets,
Kathrin

**Comment by jhoopes** [comment]
Ok. 

One last question, I'm leaning towards making this an option when you set the question up before starting a session/live quiz, but do you think this is a necessity to toggle during the quiz?  or is it fine for it to always be anonymous during the quiz.

Thanks,

**Comment by Kathrin84** [comment]
I think that should be a decision of the trainer before starting a session. As it is important that he cannot reveal names to given answers in this mode (for reasons of trustiness on side of the students), it would be contra productive if this mode could be toggled during the quiz.

What do you think?

**Comment by jhoopes** [comment]
Hi Kathrine, this feature is now added to all versions.  I'll be posting it on Moodle.org shortly

**Comment by Kathrin84** [comment]
Thanks a lot for your work! I'm looking forward to try it out. :)

**Comment by Kathrin84** [comment]
Hi,
finally I've tested your implementation in our Moodle 2.9 development system. It works fine for displaying the quiz in front of the students. There the answers are anonymized.
However the student's answers can be revealed later on by the teacher. 
So it's not an entire anonymized feature. Do you think it's possible to add this, that the students feel free to answer honestly because they know that the teacher cannot find out what answer a specific student gave?

Kind regards
Kathrin

**Comment by Kathrin84** [comment]
@jhoopes 
Hi John, for our purposes, it would be really useful if the anonymized mode would not just be active when the active quiz is live, but also if it would store the users responses in an anonymized form in the database. Additionally there should be no transfer to the grade book in this mode.
The identities should really be anonymized and the teacher should not be able to reveal them.

Do you think you could implement this addition? If so, what time for implementing would you estimate?

Thanks in advance!
Kathrin
