### ISSUE TITLE
Feature Request: add a setting to disable / enable question types

### ISSUE THREAD

**Issue by Kathrin84** [jhoopes/moodle-mod_activequiz#19]
Hi,

it's me again. ;)

While testing your plugin with all of our installed question types, we ran into some usability displaying issues with some of them.

So we thought, it would be nice as an admin to have the possibility to disable question types within this activity. There also might be question types that make no sense in a live testing.

With this setting, trainers could only choose question types that are intended (in our admin opinion) to be used with your activity. 

Kind regards,
Kathrin

**Comment by Kathrin84** [comment]
Hi again,

I just wanted to ask if you think you would like to implement this feature in the near future?

I think that if users could select question types that won't work well with your plugin, the acceptance and satisfaction for the whole great plugin could shrink. And this would be really a pity.

Kind regards
Kathrin

**Comment by jhoopes** [comment]
Hi Kathrin, (@Kathrin84)

I apologize for my absence, I'm actually in the middle of moving jobs, on top of a bunch of other things going on, not that I'm leaving development of this plugin, just that it's been a bit busy for me.

Could you please read my comment on Andrew's pull request (https://github.com/jhoopes/moodle-mod_activequiz/pull/21)  and comment about what you think?  Thanks so much for your contributions and help with making this a better plugin.

John

**Comment by Kathrin84** [comment]
Hi John,

thanks for your response.
Andrew is implementing this feature on our order. I also gave him the feedback that users still can create disabled question types.

The option with question types that are greyed out in the list is good for me, too.
However, if there could be a description for the user, then the option with dropping disabled question types from the list would be maybe a bit better.
So the user just sees the possibilities and not the restrictions. He gets a list with what he can do and not a large list with a lot of question typed he cannot use.
Might make a psychological difference.

What do you think?

Greets,
Kathrin

kiz - Abteilung Medien
Team Web & Teaching Support
Universität Ulm
89069 Ulm, Germany
Telefon: +49 731 50 31460
E-Mail: kathrin.osswald@uni-ulm.de <mailto:alexander.bias@uni-ulm.de>

**Comment by jhoopes** [comment]
This has been added to the plugin
