### ISSUE TITLE
CSS selector's scope

### ISSUE THREAD

**Issue by mudrd8mz** [jhoopes/moodle-mod_activequiz#2]
CSS selectors like `.close` or `.loading` can easily affect other HTML code outside of your module scope. Note that your styles.css is concatenated with all other plugins and core components CSS files. For that reason, it is important to use selectors that affect only you module's code.

See more information at https://docs.moodle.org/dev/Plugin_contribution_checklist where we generally suggest to use the frankenstyle prefix of other ways of making sure your selectors are well namespaced.

**Comment by mudrd8mz** [comment]
Hi John. I am not sure this is enough. The styles.css still provides CSS for classes like `.question_save`. So any HTML in the Moodle that ever uses such a class name may be affected. The approach that seems to work is to use selectors like `.path-mod-activequiz .question_save` as the Moodle core automatically puts the path-* classes to the <body> tag.

**Comment by jhoopes** [comment]
I see.  For now I also added an .activequizbox class before the .question_save to make it specific to the one I want.  I'll work on getting them all to be more specific based on the .path-mod-activequiz when I update the renderer to use separate renderers for each of my controllers.  Didn't realize Moodle added that capability.  makes it super nice to not have a huge renderer file :)
