### ISSUE TITLE
Moodle 3.0 version not available

### ISSUE THREAD

**Issue by colin-umn** [jhoopes/moodle-mod_activequiz#26]
Hi John - What are your plans (if any) for creating a Moodle 3.0 compatible version of this plugin?

**Comment by jhoopes** [comment]
Hi colin,

Hopefully this week I'll be able to release it.  I had hoped to finish some of the other work that I've been working on, but haven't been able to yet.  So, I'll just do updates to make sure it works with 3, and release it and release the other changes later.

John

**Comment by jhoopes** [comment]
Hi colin, I apologize for not updating you sooner, but there's been a version 3 out for few weeks now, just forgot to update this ticket.  

Sorry again, and let me know if you have any issues with it.
