### ISSUE TITLE
Issues from Moodle plugin comments

### ISSUE THREAD

**Issue by jhoopes** [jhoopes/moodle-mod_activequiz#28]
from @mpetrowi

Hi John,

We do have a couple suggestions for improvements which have come up:

1. Allow questions to have a max score of 0. This is useful when there are technical problems and instructors want to cancel-out a question.
2. Have regrade actually regrade the question attempts. For example if a question has an error which is fixed after the fact by the instructor.

**Comment by jhoopes** [comment]
Hi Matt,

For the first thing, would it be more useful to remove the question entirely from the quiz?  or is it that the instructor just doesn't want it to affect the score of the quiz?  

For the second, I can work on getting that in.   How urgent is it needed?  

I'm currently working on a new major version of the plugin that'll have other changes as well, like a more pluggable reporting system so that other report types are available (overview, detail, csv/excel export, etc.), changes into the UI for the instructor, and the ability to add/remove questions during the quiz, as well as other changes and usability.

I'm also going to be working on better documentation on moodle.org as well.

John

**Comment by mpetrowi** [comment]
Hi John,  It's good to hear from you!  None of the issues are pressing right now, but I'm sure they will come up again next semester.  I've been asked to 'fix' grades on questions twice this semester, and that involves some delicate DB manipulation.

For 1. Either way is fine.  Allowing the score to be 0 seems somewhat easier, although removing a question might be preferred by some instructors.

For 2.  It all sounds great.  The quiz overview report has regrade code which looks relevant and straightforward.

Thanks, -matt

**Comment by kbink** [comment]
Hi John,

I thought I'd join in.  We met at the Moodle Moot in MN this past summer.  We have started using active quiz, and have run into the same problem.  We set the percentages in the question incorrectly.  resetting the percentages in the question bank and regrading the active quiz did not work for us.  We tried setting the question points to zero so it wouldn't count, and that didn't work.  We tried deleting the question but that also did not change grades, even with a regrade.  I think mistakes like this are going to be common, especially with new users and some way to make corrections would be fantastic.  Right now we are down to viewing each of the 80 students individually to correct the score for the one question we had wrong.  Ideally changing it in the question bank and regrading would change scores, but I'm not sure how possible that is in the code.
Kalli

**Comment by jhoopes** [comment]
Hi Kalli @kbink and Matt @mpetrowi ,

This is actually pretty possible.  The question engine provides an interface for it to regrade all attempts on an attempt by a student.  I haven't gotten to it yet mostly because it wasn't super urgent from Matt.

As I can see that it's probably more important for these things sooner than later, I can start working on this now.  

Please reference #31 for the checklist of items I'm hoping to work in for v3.7, which will be a stepping stone to version 4.

Let me know if you have any objections/questions.

**Comment by jhoopes** [comment]
Hi Kalli @kbink and Matt @mpetrowi 

Can you please try out the 3.7 branch, and see if you find any issues with it and what you're wanting?
https://github.com/jhoopes/moodle-mod_activequiz/tree/v3.7

Thanks,
John

**Comment by mpetrowi** [comment]
Hi John,  Thanks.  We'll test the new changes this week

**Comment by kbink** [comment]
Our Moodle Admin installed this on a 3.0 test site for me.  At first
attempt, it appears to work!  I ran a session, answers things as the
instructor on the page.  Closed the session.  Went into Question bank and
changed the answer percentages, saved.  Back into active quiz, that
session, hit regrade, back to the session and the score had changed.  I
want to do more testing but it is looking good!



On Sun, Jan 31, 2016 at 9:55 PM, jhoopes <notifications@github.com> wrote:

> Hi Kalli @kbink <https://github.com/kbink> and Matt @mpetrowi
> <https://github.com/mpetrowi>
>
> Can you please try out the 3.7 branch, and see if you find any issues with
> it and what you're wanting?
> https://github.com/jhoopes/moodle-mod_activequiz/tree/v3.7
>
> Thanks,
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhoopes/moodle-mod_activequiz/issues/28#issuecomment-177749058>
> .
>



-- 
Kalli-Ann Binkowski
Academic Technology Coordinator
Research and Learning Technologies
College of Biological Sciences
(612) 624-0641
kbink@umn.edu

**Comment by jhoopes** [comment]
This seems to be fixed according to comments so closing issue.
