### ISSUE TITLE
AJAX scripts should check for permissions, too

### ISSUE THREAD

**Issue by mudrd8mz** [jhoopes/moodle-mod_activequiz#3]
It seems to me that `\mod_activequiz\controllers\quizdata::setup_page()` and the `quizinfo.php` should also check for a required capability. Or am I missing something?

**Comment by jhoopes** [comment]
Thanks for catching this.  I do check for permissions on the quiz data class, except that the capability checks are within each specific action.  Most of those actions will only work if the user has the capability for controlling the quiz.   (The $this->RTQ->is_instructor() method performs this check)

However, after thinking about it, I did neglect to check for login capability for the course and course modules in both files.  I will be adding that here shortly

**Comment by mudrd8mz** [comment]
Great, thanks for checking this.
