### ISSUE TITLE
Students able to get multiple attempts on questions

### ISSUE THREAD

**Issue by mpetrowi** [jhoopes/moodle-mod_activequiz#39]
Hi John,

Here is some feedback from our support staff:

There seems to be a problem with multiple choice questions for active quizzes. It seems that when a multiple choice question is in progress, the person taking the quiz is able to select an answer, save it and see "This answer is incorrect", then refresh the page and be able to select a different answer that is correct. The instructor can see in the results that the student answered, refreshed, and answered again. When we were testing it, the problem was occurring on both mobile devices and computers. Please let us know if you would like us to do additional testing on the problem, or if you have any questions.

Hopefully this is an easy fix.

Thanks,
-matt

**Comment by jhoopes** [comment]
Hey @mpetrowi,

Thanks for reporting this.  I also saw this a few days ago when testing and prepping for the new release.  So far I haven't found why this is happening.  I planned on taking a closer look tonight, so thanks for reporting this issue as well.

John

**Comment by jhoopes** [comment]
Hey @mpetrowi 

This should be fixed with the commit referenced here.  I'll be hopefully pushing out version 3.7 this evening.

John

**Comment by mpetrowi** [comment]
Thanks John!  I'll upgrade our sites over Spring break (~ 3/20)
