### ISSUE TITLE
Why are there global statements in scripts like view.php?

### ISSUE THREAD

**Issue by mudrd8mz** [jhoopes/moodle-mod_activequiz#4]
In the current view.php (and probably other places like edit.php) code like

    require_once("../../config.php");
    require_once($CFG->dirroot.'/mod/activequiz/lib.php');
    require_once($CFG->dirroot.'/mod/activequiz/locallib.php');
    require_once($CFG->libdir . '/questionlib.php');
    require_once($CFG->dirroot . '/question/editlib.php');
    global $CFG, $DB, $PAGE, $OUTPUT;

what is the point of the `global` declarations? These scripts are
supposed to be always executed directly from the HTTP request in the
global scope, not included into a functions. Am I missing something?

**Comment by jhoopes** [comment]
These were just put there so my IDE knows about the variable and how to find the classes for auto completion.  I'll remove them

**Comment by mudrd8mz** [comment]
>  I'll remove them

Oh I see. No need to remove them, making your IDE happy is a valid reason. Might be good to have a short inline comment there to make it explicit. Please feel free to put it back as needed.
